### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by River-Zhang** [zyr17/Learning-deep-representation-for-trajectory-clustering#1]
Could you please provide the dataset used in your code? Thanks very much!

**Comment by xiaozhangtongx** [comment]
大佬，你好，能否分享一下方法代码里面的数据，谢谢，辛苦了；欢迎邮箱交流:jufuzhang0917@163.com

**Comment by zyr17** [comment]
Sorry, it is not the official implementation, and the data used in our experiment is not publicly available.

**Comment by River-Zhang** [comment]
不好意思，我也没有收到数据

从 Windows 版邮件发送

发件人: xiaozhangtongx
发送时间: 2022年7月22日 22:15
收件人: zyr17/Learning-deep-representation-for-trajectory-clustering
抄送: River-Zhang; Author
主题: Re: [zyr17/Learning-deep-representation-for-trajectory-clustering]Data (Issue #1)

***@***.***
